apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClass: ""  # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-dynamic
  accessModes:
  - ReadWriteOnce
  resources:
    request:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1b
  volume:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx--ebs-dynamic
spec:
  type: load-balancer
  selector:
    purpose: ebs-dynamic
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
    nodePort: 30007