apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkins.url: "http://jenkins.joindevops.com/build/job/5"
    image registry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx