apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "68 Mi"
        cpu: "100m" #1/10th of cpu
        # provide equal/more than requests
      limits: 
        memory: "100 Mi"
        cpu: "120 m"
